### ISSUE TITLE
Feature Request: Add a world type that prevents the generation of modern biomes

### ISSUE THREAD

**Issue by SimplyTadpole** [Crystalis7/Hybrid-Beta#12]
This is the only mod that provides proper beta terrain generation for version 1.19.2 on Fabric and Quilt (Modern Beta explicitly refuses to support it, and Cabbage's Retro Generator is bugged and does not spawn passive mobs or structures), but this mod lacks something the others do: the ability to only have beta biomes. If doing a playthrough that recreates elements of the beta, the immersion is broken by seeing the several biomes added since release generating everywhere.

I understand you're likely not seeking to provide a largely 1:1 recreation of the beta era, but would you be willing to add the option to prevent modern biomes from generating, at least for the 1.19.2 version?

The only vanilla biomes that would make sense to spawn would be the default Ocean, Snowy Taiga, River, Beach, Snowy Beach, Plains, Snowy Plains, Desert and Forest for the Overworld, and Nether Wastes for the Nether.

**Comment by Crystalis7** [comment]
Hello - that is rather annoying - I suppose that 1.19.2 is the only version you can use?

As you say, this datapack/mod is not seeking to recreate beta terrain 1:1, and it is not completely possible to do so within the framework that I have created the pack (this is really just a datapack wrapped up into a Fabric/Kotlin mod, whereas Modern Beta is a full-on mod to the terrain generation engine).

Creating a version that only includes beta biomes is something that I would consider, although there are many more beta biomes than just the ones you mention - see [this](https://minecraft.fandom.com/wiki/Biome/Before_Beta_1.8) wiki page. If I were to make this version, it would have those biomes, plus oceans and rivers. Beach biomes are not entirely necessary (the sand and gravel beaches will generate even if there is no 'Beach' biome present), but I could probably include them in order to allow turtles to spawn. I could send you a bare-bones datapack now which will override the Hybrid Beta biomes, but this would require the biomes you want included to be created from scratch (assuming you wouldn't want to wait until I make them). If you know anything about making biome datapacks, then this is something you could try, or if not, it could be a fun learning exercise. Otherwise, I will see what I can do in terms of making this version myself, but it will likely take a bit of time since I am currently working towards the next major feature release of this datapack.

In terms of the nether, it is beyond the scope of something that I would include in this pack. However, seeing as it is so easy to do, I just went ahead and made a datapack which just removes all nether biomes except for the nether wastes (attached). It should be compatible with Minecraft 1.19.2 up to 1.20.1.
[Clear_Nether.zip](https://github.com/Crystalis7/Hybrid-Beta/files/12255744/Clear_Nether.zip)

**Comment by SimplyTadpole** [comment]
Hi, thanks for responding ^^

Yeah, for the time being 1.19.2 is the only version that has compatibility with several key mods I wanted to use for a beta-themed modpack (Dimensional Doors [only up to 1.19.3], World Host [does not support 1.19.3], and From the Fog [does not support 1.18.2]), but Modern Beta does not support 1.19.2, which is why I hoped to use Hybrid Beta to accomodate for it.

I understand it's tricky to do, I'm sorry for having assumed. And thanks for refreshing my memory on the biomes, it's been over a decade since I last played Beta 1.7.3 so I was rusty ^^' But, at least until you implement the proper beta biomes, the aforementioned list of biomes could at least help provide an experience that is *largely* similar to the beta biomes as a placeholder. I'm not familiar with making biome datapacks at all, so if I were to do my own datapack similar to the one you made for the Nether, where do I get started? I tried looking at the minecraft jar for 1.19.2, but it doesn't have a `data/minecraft/dimensions` folder :/

Thank you again for taking the time to respond and offer help/advice though, and I hope the next version upgrade goes well c:

**Comment by Crystalis7** [comment]
Hello - I actually just went ahead and made an addon pack with just the beta biomes. It's not super polished, but should have everything there. Let me know if you have any issues/need any help with it.

[Beta Biomes Addon.zip](https://github.com/Crystalis7/Hybrid-Beta/files/12267454/Beta.Biomes.Addon.zip)

**Comment by SimplyTadpole** [comment]
Thank you, that worked well! The only problem was that structures (including villages) weren't spawning, but I managed to fix that on my own (though I did have to look at Modern Beta's way of handling it to serve as a guideline lol) - I'm uploading it here:

[HybridBetaBiomesAddon.zip](https://github.com/Crystalis7/Hybrid-Beta/files/12284526/HybridBetaBiomesAddon.zip)

Maybe you could upload it on Modrinth as an optional add-on for those who wish to also have a beta-accurate experience on 1.19.2 specifically? Either way, as there's a supply to this demand now, I'm gonna be closing this issue for now ^^'
