### ISSUE TITLE
Incompatible with Project vibrant journeys

### ISSUE THREAD

**Issue by Wizrat** [Crystalis7/Hybrid-Beta#15]
the 1.19.2 version of this datapack is sadly incompatible with project vibrant journeys which prevents many of the things in Project vibrant from generating this is most likely due to them both being addons that change the world gen in some way

**Comment by Crystalis7** [comment]
Hello - are you saying that the worlds load, but many of the features you are expecting from the mod are not generating?

Taking a quick look at the mod, it appears that it does not really affect the terrain, rather it is adding more generated features to each biome. With that in mind, if it is just the terrain generation you want from my datapack, then you could try navigating to `/data/minecraft/worldgen` and deleting the `biome` folder. This way, my overrides of the vanilla biomes will no longer apply, and so that may result in the mod's changes being applied instead.

**Comment by Wizrat** [comment]
Thank you this worked perfectly! have a lovely day!

**Comment by Crystalis7** [comment]
Glad to hear it- have a great day yourself!
