### ISSUE TITLE
Surface caves seem to be really short

### ISSUE THREAD

**Issue by tmewett** [Crystalis7/Hybrid-Beta#20]
Thanks for making this datapack, I really like beta worldgen.

I have noticed though that surfaces caves seem to end really quickly and don't go anywhere. We've generated 2 worlds now and explored a lot and this aspect feels quite different to vanilla Minecraft and what I remember of old beta. I don't know if I'm misremembering beta, just unlucky, or if this datapack has affected this?

**Comment by Crystalis7** [comment]
I'm glad you like to pack. This is interesting - I haven't made any explicit changes to cave generation aside from

- Making it less likely for cave entrances to generate very near to a river
- Reducing the proportion of flooded caves

Neither of these should affect how long caves are (though perhaps the first point will suppress caves which try and pass through a river). I will have a look myself.

**Comment by Hyperbus02** [comment]
I believe this is because nothing too major about caves was changed by Cascades ironically. The small tube caves the game has always had were severly nutured in the Caves and Cliffs overhaul and for the most part dead-end almost right away. To my understanding, there's no projects that port the beta caves to post-beta versions.

**Comment by Crystalis7** [comment]
It turns out that there were some issues with cave entrances that I have now resolved in v1.0.4
