### ISSUE TITLE
Add an uninstall function

### ISSUE THREAD

**Issue by No-Git-Tag** [Crystalis7/Hybrid-Beta#23]
Hello!
I am aware that the modrinth page states that this datapack cannot be removed once installed, but It would be nice to have an uninstall function. If this can't be done, I would appreciate to know why it can't be done.
I am clueless when it comes to world-gen datapacks, so please forgive me if the reason is seemingly obvious.

**Comment by Crystalis7** [comment]
Hello - unfortunately this is a limitation with datapacks which add new content. In this case, it is specifically because this pack adds new biomes. If you remove the datapack, Minecraft will error when it encounters existing parts of the world which are one of the new biomes, This is because it no longer has the information from the datapack which provides information on certain properties of the new biomes, for example, what colour to set the grass, leaves, and sky in that new biome, or which mobs to spawn there.

Incidentally, I have recently released Cascades: Source (available in the Releases section of this repository) which is a slimmed-down version of the pack which does not add any new biomes - rather it only modifies the terrain shape. I just tried loading a world with that pack, and then removing it afterwards, and it seems to load, though there are harsh chunk borders between regions loaded with the datapack, and regions loaded after removing it.
