### ISSUE TITLE
Clay missing from Rivers. (Cascades-v1.0.3-1.20.x)

### ISSUE THREAD

**Issue by primetoxinz** [Crystalis7/Hybrid-Beta#32]
As per title,
Clay doesn't generate in Rivers, probably due to them not usually being proper minecraft:river biomes

**Comment by JaXStutz** [comment]
Not the author but clay spawns at the bottom of lukewarm & deep lukewarm oceans.

Reasoning:
"Since the old sand and gravel beaches have been re-added, this means that the (unsightly) sand, gravel and clay blobs have been removed. An implication of this would be that clay and gravel are more difficult to find. To make up for this, clay can now be found at bottom of lukewarm oceans and deep lukewarm oceans."

**Comment by Crystalis7** [comment]
JaXStutz is correct. I have purposefully removed clay and gravel from rivers.
